php/actions/get_filtered_list_topics.php

Хотелка [#003](https://rutracker.org/forum/viewtopic.php?p=61052536)

Дата создания релиза на Главной.

---

index.php
js/subsections.js
js/topics.js

Хотелка [#014](https://rutracker.org/forum/viewtopic.php?p=61052536)
И немного рефакторинга.
Добавлена задержка регенерации списка в 2 с. после добавления раздач в
клиент.

Количество и объём отфильтрованных раздач.

---

php/actions/get_filtered_list_topics.php

[fix] PHP Notice при отключеннных средних сидах.

---

index.php
js/topics.js
php/actions/get_filtered_list_topics.php

It would be useful, for example, for working with black lists to manage all topics from certain subsection.

Add field to search by subsection id.

---

php/actions/add_topics_to_client.php
scripts/jquery.topics.js

-  Fix marking of newly downloaded topics in DB. Because of the issue the corresponding topics did not disappear from the mail Web-TLO list.
- Perform the mail list refresh after a double click on a keeper nick from the list.

Fix small UI behavior issues

---

css/style.css
index.php
php/actions/get_filtered_list_topics.php
scripts/jquery.topics.js
scripts/jquery.widgets.js

Draw "from"/"to" fields to filter results by number of users keeping the corresponding releases. Show it only when `is_keepers` is checked.

Add keepers count filter

---

index.php
php/actions/add_topics_to_client.php
php/actions/exec_actions_topics.php
php/actions/tor_client_is_online.php
php/classes/clients.php
php/classes/flood.php
php/common/control.php
php/common/tor_clients.php

Flood can be used with rtorrent/qBittorrent/Transmission/Deluge as underlying client.

Added support for Flood webUI as a client.

---

php/classes/qbittorrent.php

Sorry, mess up with branches.
Continue this #140

qBittorrent: add hashv2 support

---

php/actions/get_filtered_list_topics.php
php/actions/get_list_subsections.php
scripts/jquery.subsections.js

Добавлена возможно добавить подраздел в хранимые из списка раздач "из прочих подразделов". Может быть удобно в случае массового переноса раздач в другой раздел.

Add subsection from unsaved

---

php/actions/get_reports.php
php/common.php
php/common/reports.php

Move code to function.
If, somehow, version is empty - do not post any info to forum report

Web-TLO version fix

---

scripts/jquery.actions.js
scripts/jquery.common.js
scripts/jquery.widgets.js

Added check save settings, when they changed

---

index.php
php/actions/set_config.php
php/common.php
php/common/control.php
scripts/jquery.tor_clients.js
scripts/jquery.widgets.js

new option
If set, script control.php will manage all topics in client, not only set subsections.
Example of unadded subsection:
```
С включённой регилировкой "других" подразделов:
25.12.2022 15:15:33 Начат процесс регулировки раздач в торрент-клиентах...
25.12.2022 15:15:35 Получаем раздачи торрент-клиента "qbkeepmain"
25.12.2022 15:16:07 Получение раздач завершено за 31s
25.12.2022 15:16:11 Поиск раздач в БД завершен за 3s
25.12.2022 15:16:11 Используется зеркало для API: https://api.t-ru.org
25.12.2022 15:16:11 Получение данных о пирах...
25.12.2022 15:16:25 Обработка раздач раздела 185 (1900 шт) завершена за 13s
25.12.2022 15:16:48 Обработка раздач раздела 357 (3268 шт) завершена за 23s
25.12.2022 15:16:54 Обработка раздач раздела 1105 (714 шт) завершена за 5s
25.12.2022 15:16:58 …
```

Added option to manage unadded subsections

---

Dockerfile
docker-compose.yml
docker/rootfs/etc/php81/php-fpm.d/www.conf
docker/rootfs/etc/s6-overlay/s6-rc.d/_setup-storage/type
docker/rootfs/etc/s6-overlay/s6-rc.d/_setup-storage/up
docker/rootfs/etc/s6-overlay/s6-rc.d/cron/run
docker/rootfs/root/_setup-storage.sh

Fix #148 
This commit effectively moves location of all data, managed by webtlo, to `/data/storage`.

Docker fixes

---

scripts/jquery.actions.js
scripts/jquery.subsections.js
scripts/jquery.tor_clients.js

fix #155
Change trigger event for update client/subsection dataset

Spinner trigger fix, change to spinstop event

---

scripts/jquery.actions.js
scripts/jquery.common.js

fix #151
change highlight  trigger

highlight save button, in unsaved state

---

php/common/control.php

Fix #162 
Empty control_peers value is now counted correctly.
Move `get_control_peers` to execute it less times.

Fix contol_peers for zero values

---

php/actions/get_list_subsections.php

Exclude useless for keeper empty subsections from selector

Exclude empty sections from selector

---

index.php
php/actions/get_filtered_list_topics.php
scripts/jquery.topics.js
scripts/jquery.tor_clients.js

1. Add client name in topics list.
3. Add filter by client name (auto update list on add new client). Can be selected from list on dblclick.

Show client name in topics list, filter by client name

---

index.php
php/actions/get_filtered_list_topics.php

add new filter by topic_id

---

php/actions/get_reports.php
php/actions/get_reports_hashes.php
scripts/jquery.common.js
scripts/jquery.topics.js

Follow #106
Move logic to another endpoint.
Fix blocking buttons and messaging

migrate get_report_hashes to individual endpoint

---

php/actions/get_filtered_list_topics.php

remove spaces from filter_phrase

---

php/actions/get_filtered_list_topics.php

Based on #205 and [wiki](https://keepers.tech/misc/arrow_types/)

add title to topics and keepers bullets

---

php/actions/get_recovery_list.php

Use torrent completion value from DB as we are not fetching it from client now

check if torrent fully downloaded when recovering

---

php/actions/get_filtered_list_topics.php
php/common/update.php

Exclude self from keepers-seeders when "исключить себя из списка хранителей раздачи" is checked.
Resolves #224

Fix filter after 1f56fd5

---

php/common.php
scripts/jquery.subsections.js

Close #223
Предлагать раздачи с кол-вом сидов 3 =>5
Предлагать раздачи с датой релиза старше 0=>5 дней
Средние сиды - включить
Хранить разды по номеру темы - включить по-умолчанию

Config update

---

index.php
php/actions/get_reports.php
php/actions/set_config.php
php/common.php
php/common/reports.php
scripts/jquery.subsections.js
scripts/jquery.tor_clients.js

1. Use previosly hidden option `exclude` and add it to UI. Now you separatly exclude subsections and/or client.
2. Total exclude list post here, show `auto_clear_messages` option
3. Config.ini
```
[reports]
exclude_clients_ids="1"
exclude_forums_ids="185,908"
auto_clear_messages="0"
```
4. Add more logs, to see excluded topics:
```12.01.2023 22:51:36 Начат процесс отправки отчётов...
12.01.2023 22:51:36 При создании отчёта исключены торрент клиенты: 1   #<< это ид
12.01.2023 22:51:36 При создании отчёта исключен подраздел № 908
12.01.2023 22:51:41 Notice: Не получены данные о хранимых раздачах для подраздела № 1605 #<< Не найдены данные, потому что весь раздел хранится в исключённом клиенте
12.01.2023 22:51:45 Найдено хранимых раздач 1 шт для подраздела № 773
12.01.2023 22:51:51 Notice: …
```

Exclude clients and subsections from sent reports

---

index.php
php/actions/set_config.php
php/classes/db.php
php/classes/settings.php
php/common.php
php/migration/Backup.php
php/migration/DatabaseMigration.php

Close #231, #222
* При изменении pragma_version будет сделан бекап файла БД.
* При изменении user_version будет сделан бекап файла конфига.
Бекабы хранятся рядом с конфигом в подпапке `/data/backup`.
При сохранении настроек будет создаваться публичная версия конфига, `config_public.ini`, в которой нет паролей к форуму.
Переписан алгоритм создания БД при первичном запуске ТЛО. Актуализированы sql-запросы создания таблиц и триггеров.
Алгоритм обновления БД, повышением версий по одной вынесен в отдельный алгоритм.
Добавил проверки версии БД, при даунгрейде версии ТЛО, что может приводить к интересным последствиям.
Прочие оптимизации кода при работе с БД и файлом конфига.

Автоматический бекап конфига и БД при изменении версии.

---

php/actions/get_reports.php
php/classes/ReportCreator.php
php/common/reports.php

Display popular topics in reports as a measure to a constant confusion of regularly disappearing keeping material.

Post >10 seeds topics in reports

---

php/actions/set_config.php
scripts/jquery.common.js

Close #239
Формат передачи массива конфига изменён на json для обхода ограничения количества POST переменных.

Config. Fix huge config saving

---

.github/workflows/sub-build-docker.yml
.github/workflows/sub-build-zip.yml
src/back/WebTLO.php
src/css/style.css
src/index.php
src/probe.php
src/scripts/jquery.subsections.func.js
src/scripts/jquery.subsections.init.js
src/scripts/jquery.topics.func.js
src/scripts/jquery.topics.init.js
src/scripts/jquery.widgets.init.js

* Исправлены ошибки в html.
* Добавлено автоматическое сохранение выбранной вкладки опций в куки.
* Исправлены различные опечатки в описаниях.
* Увеличена задержка при автоматическом применении фильтра с 600мс до 1500мс.
* При успешной загрузке описаний раздач (имена + прогресбар), фильтр будет применятся автоматически.
* В случае какой-либо критической ошибки при инициализации ПО (проблема с БД), будет красная плашка с тексом ошибки.
* Расширена выводимая информация на вкладке "О программе". Добавлена ссылка на `probe.php`.
* Тип установки добавлен в автоматические сборщики ci.

Дополнение вкладки "О программе"

---

src/php/actions/add_topics_to_client.php
src/php/actions/check_mirror_access.php
src/php/actions/check_new_version.php
src/php/actions/clear_log_content.php
src/php/actions/count_topics.php
src/php/actions/exclude_topics.php
src/php/actions/exec_actions_topics.php
src/php/actions/get_filtered_list_topics.php
src/php/actions/get_list_subsections.php
src/php/actions/get_log_content.php
src/php/actions/get_recovery_list.php
src/php/actions/get_reports.php
src/php/actions/get_reports_hashes.php
src/php/actions/get_statistics.php
src/php/actions/get_torrent_files.php
src/php/actions/get_user_details.php
src/php/actions/set_config.php
src/php/actions/tor_client_is_online.php

Close #287
Исправил подключение vendor/autoload в actions/*.php

Fix actions autoload include

---

src/back/Helper.php

Исправил функцию natsortField.
- Пустые null значения теперь равны нулю. 
- Прямое сравнение значений заменил на `<=>`
Close #295

Исправлена сортировка по пустым значениям

---

src/index.php
src/php/actions/check_new_version.php
src/scripts/jquery.common.js

Укоротил выводимое описание релиза при проверке новой версии.

---

src/back/WebTLO.php
src/composer.json
src/composer.lock

in addition to 0cdbfee38432fd0bd4aaa683b7b0fb98b7e603e8

Show sqlite version on "About" page

---

src/back/AppContainer.php
src/back/Settings.php
src/back/Static/AppLogger.php
src/index.php

Добавлены уровни ведения журнала. Info по умолчанию.
Изменение настройки влияет только на новые записи в журнале. 
Не все алгоритмы переведены на LoggerInterface, потому не все записи будут подвержены фильтрации.
close #76

Add LogLevel support

---

src/back/External/CheckMirrorAccess.php
src/index.php
src/php/actions/check_mirror_access.php
src/php/actions/check_new_version.php
src/scripts/jquery.actions.js

close #174
Переписал проверку доступа:
- для форума проверятся /myip.
- для апи форума v1/get_client_ip
- для апи отчётов v1/info/statuses
curl заменён на GuzzleHttp

Refactor check_mirror_access

---

src/back/Clients/Utorrent.php

fix #325
Добавлена обработка cookie авторизации для "современных" версий uTorrent

326 Bug: Utorrent 3.5, проблема с авторизацией

---

src/back/WebTLO.php

- Include branch and SHA in version details
- Add method to fetch Git data
- Update version initialization with Git info
close #334

334 New feature: Выводить данные о текущей версии для использующий Git

---

.php-cs-fixer.php
src/back/Module/ProbeChecker.php
src/probe.php

- Remove raw cURL (close #170)
- Add rep url to check

Refactor probe.php

---

.github/workflows/build-on-branch.yml
.github/workflows/ckeck-on-pull-request.yml
.github/workflows/sub-build-zip.yml
.github/workflows/sub-check.yml
.github/workflows/weekly-validation.yml
.gitignore
.php-cs-fixer.php
phpstan.neon
src/back/Clients/Flood.php
src/back/Clients/Qbittorrent.php
src/back/Clients/Traits/AllowedFunctions.php

fix #420
- Проверки phpstan и php-cs-fixer теперь выполняются с той версией, которая указана в `composer.lock`.
- Добавлена матрица версий php при проверке кода для PR.
- Добавлено кеширование phpstan.
- Добавлена задача еженедельной проверки кода.

CI/CD. Обновление и дополнение проверок кода

---

src/back/External/Api/StaticHelper.php
src/back/External/ApiClient.php
src/back/External/Shared/RateLimiterMiddleware.php
src/composer.json
src/composer.lock

В дополнение к #446
- Добавлен `RateLimiterMiddleware` для `GuzzleHttp\Client`.
- Добавлен контроль отправки запросов в апи форума, не более 2х запросов в 1000 мс.

Add custom RateLimiterMiddleware

---

src/back/DB.php
src/sql/0015-drop-unused-tables.sql
src/sql/9999-init-database.sql

- Db. Update pragma user_version = 15
- Drop ForumsOptions table
- Drop seeders_transfer trigger

Удалены ненужная таблица и триггер
