keepers-team/webtlo

clients.php

также добавлен код для обработки случая когда WebUI не подключен к
Deluge daemon (у меня такое происходит после перезапуска daemon'а).
Логика такова: если WebUI не подключен ни к одному daemon'у, то
подключиться к первому в списке доступных.
Т. о. если WebUI уже подключен к какому-либо daemon'у то ничего не
произойдет.
Если необходимо работать не с первым daemon'ом то следует подключиться в
нужному через Connection Manager в WebUI.
Остутствует обработка случая когда список доступных daemon'ов пуст (и
вообще возможно ли такое?).
Протестировано на Deluge 1.3.6, 1.3.11 - 1.3.15 и PHP 7.0.18-0.

Исправлена поддержка Deluge 1.3.6, 1.3.11+

---

php/classes/api.php

Похоже изменился API, и теперь функция get_peer_stats также возвращает keepers, что поломало выполнение control.php.

[fix] Починил control.php после изменения API.

---

php/classes/rtorrent.php

Исправлена ошибка rTorrent Error: Wrong object type.
Fixes #111.

[fix] rTorrent Error: Wrong object type.

---

php/classes/rtorrent.php

Полноценно используем host/port/login/password переменные, всё так же обращаемся на /RPC2.
Изменение требует адаптации конфига на стороне пользователя:
Вместо "адрес_клиента:порт" в пункте "IP-адрес/сетевое имя", порт надо перенести в соответствующее поле
/RPC2 теперь можно положить за веб-сервер, на котором и проводить аутентификацию, включая https подключение, и возможность скрыть /RPC2 куда-то вглубь веб-сервера, прописав в настройках клиента в WebTLO в параметре "порт" одновременно порт и путь в формате "port/custom/path/to" (/RPC2 добавляется сам).
Прятать /RPC2 за веб-сервер стоит потому, что XMLRPC rtorrent-а чрезвычайно опасен с точки зрения эксплуатации, как минимум за счёт команд execute.*
Веб-сервер можно настроить на обращение в unix-сокет, открываемый rtorrent'ом, с любыми …

Rtorrent за веб-сервером + аутентификация + учитывание порта

---

php/actions/get_torrent_files.php

fix #153
If selected option `скачать торрент-файлы для обычного пользователя` tracker will be replaced with `t-ru.org`
If pressed button `Скачать *.torrent-файлы выделенных раздач текущего подраздела в каталог с заменой Passkey` and no passkey provided, then tracker will be replcaed with default.
Last commit provide some additional logs.
```
Замена пасскея для обычного пользователя:
27.12.2022 23:29:55 Выполняется скачивание торрент-файлов (2 шт), трекеры пользовательские.С заменой Passkey: asd123
27.12.2022 23:29:58 before => http://bt3.rutracker.net/ann?kk=real_key,after => http://bt3.t-ru.org/ann?pk=asd123
27.12.2022 23:30:00 before => http://bt2.rutracker.net/ann?kk=real_key,after => http://bt2.t-ru.org/ann?pk=asd123
Замена паскея для хранителя:
27.12.2022 23:30:24 Выполняется …
```

Download torrent files with passkey replace

---

index.php
php/actions/set_config.php
php/common.php
php/common/control.php
scripts/jquery.widgets.js

Added an option to exclude a specified number of active seeding keepers from the peer count while control.
0 - to disable feature. Default value:3
If the actual number of active keepers is greater than the setting value it will be used.
Added some temp logs:
```
29.12.2022 22:22:22 Получение данных о пирах...
29.12.2022 22:22:22 hash=> config:3 => forum_keepers:1 => calc_keepers:1 => seeders:3 => calc_peers:2
29.12.2022 22:22:22 Обработка раздач раздела 773 (1 шт) завершена за 0s, лимит сидов 8
29.12.2022 22:22:23 hash=> config:3 => forum_keepers:0 => calc_keepers:0 => seeders:50 => calc_peers:50
29.12.2022 22:22:23 hash=> config:3 => forum_keepers:0 => calc_keepers:0 => seeders:84 => calc_peers:84
29.12.2022 22:22:23 Обработка раздач раздела 1605 (2 шт) завершена за 0s, лимит сидов 10 …
```

Control keepers

---

php/common/control.php
scripts/jquery.widgets.js

fix #179 
If config settings set to `""`, change it to `-2` in calculations, so `get_control_peers` operate only int values.

fix control peers calculation with empty string value

---

.htaccess

There is no need to keep configuration blocks for unsupported versions

Replace outdated configuration in htaccess

---

index.php
scripts/jquery.topics.js

Click on `reset` button will save current filter preset to Cookies and reset filters to default.
Ctrl+Click on `reset` button will try to restore saved filter preset if it exists.

add simple click-ctrlclick reset-restore logic

---

php/actions/get_filtered_list_topics.php
php/common/tor_clients.php

fix #203 
1. If forum api return status=7, exclude it from valid topics.
`get_tor_topic_data?by=hash&val=728A236C40101F1371C3A9B3CED1289D032DE1FB`
```
"6294505": {
"info_hash": "728A236C40101F1371C3A9B3CED1289D032DE1FB",
"forum_id": 1726,
"poster_id": 28380987,
"size": 369855200,
"reg_time": 1670791290,
"tor_status": 7,
"seeders": 10,
"topic_title": "(Hard Rock) [CD] Skid Row - The Gang's All Here - 2022, FLAC (image+.cue), lossless",
"seeder_last_seen": 1673835661,
"dl_count": 356
}
```
2. Include undone Torrents in unregistered search.
If torrent has not yet been fully downloaded, but its status has changed on the forum - we will find out about it.
4. Fix arrow type for main page (1=upload, 0=download, null=else).

Fix unregistered topics search

---

index.php
php/actions/get_filtered_list_topics.php
scripts/jquery.common.js
scripts/jquery.topics.js

Добавлено отображение счётчиков раздач в чёрном списке из выбранного подраздела. 
При подсчёте учитываются фильтры статуса и приоритета раздачи и тип "хранения".

Show excluded(blacklisted) topics in counter

---

docker/rootfs/etc/crontabs/root
docker/rootfs/etc/s6-overlay/s6-rc.d/cron/run

Close #201 
Исправил запуск cron внутри контейнера, теперь запустк от `root` пользователя. Это исправляет проблему, что крон не запускался вообще, но может принести новые проблемы с правами.
Локально, создаваемые запущенными задачами лог-файлы читаются ТЛО нормально.
Добавил control.php в задачи, т.к. его выполнение можно отключить в настройках ТЛО.

Docker. Add control.php, fix permisions

---

php/classes/db.php
php/common.php
php/common/forum_tree.php
php/common/high_priority_topics.php
php/common/update.php
php/migration/DatabaseMigration.php

Рефакторинг алгоритмов:
- получения дерева подразделов `forum_tree`
- получения списка высокоприоритетных раздач `high_priority_topics`
- обновления списка раздач хранимых подразделов `update`
Обновление таблицы `Topics`:
- добавлены поля `poster_id` - ид автора раздачи, `seeder_last_seen` - последняя активность сидов
- исправление триггера обновления таблицы при вставке дублей
- добавлен индекс по ид подраздела для статистики
- поднята версия БД до 10
- подкорректированы скрипты миграции и первичного запуска для 10й версии
Новые поля в БД будут нужны для: #74, #90, #206
Исправил скрипт миграции до db_version_8. Теперь имеющиеся записи о хранимых раздачах в таблице `Clients` будут копироваться в новую таблицу `Torrents` при пересоздании таблиц, #157.

Refactoring actions, Topics table

---

scripts/jquery.actions.js
scripts/jquery.topics.js

Close #242 
Использован существующий признак `filter_hold`. Если он задан, то выполнение поиска раздач будет поставлено в "очередь", до тех пор, пока не выполнится обновление сведений или не завершится выполнение текущего поиска.

Filter. Put new topics query on hold when some tasks are running

---

php/classes/settings.php

Использование file_put_contents() в редких случаях может вызвать гонку и повреждение конфиг файла.

Атомарное сохранение конфиг-файла.

---

php/classes/reports.php

Close #248
Добавлена замена спецсимволов в никах хранителей, чтобы ники типа `nick&nick` заменялись на `nick&amp;nick`, ведь именно в таком виде никнеймы хранителей ТЛО получает от апи трекера.

Reports. Add htmlspecialchars for keeper_name

---

php/classes/flood.php

Forgot to remove the prototype-stage override of savepath to empty, so that the default would be used.

Flood: fixed save path for new torrents

---

docker/rootfs/etc/php81/php-fpm.d/www.conf

Other versions already come with such configuration set, except for OpenServer ones where it's up to the user to change settings.

docker: allow up to 100k input vars

---

docker/rootfs/etc/php81/php.ini

При запуске cron job'ов используется базовый /etc/php81/php.ini, у него по умолчанию выставлен memory_limit = 128M.
Добавил базовый php.ini с выставленным лимитом в 2G

added /etc/php81/php.ini file with memory_limit = 2G

---

.github/workflows/build-on-branch.yml
.github/workflows/build-on-tag.yml
.github/workflows/sub-build-docker.yml
.github/workflows/sub-build-zip.yml
.github/workflows/sub-metadata.yml
src/back/WebTLO.php
src/css/style.css
src/index.php

- Добавлена запись в version.json текущей версии ПО при пуше ветки/тега. 
- Добавлена запись sha-коммита.
- Добавлено визуальное отображение sha-коммита и ссылки на него.
- Для win-standalone убрано composer dumpautoload, для упрощения обновления с заменой файлов.

CI. Автоматическая запись версии ПО в version.json из тега/названия ветки

---

src/php/actions/check_new_version.php
src/scripts/jquery.common.js

Проверка новой версии теперь получает ссылку на конкретный релиз, в зависимости от типа установки.
`standalone` => `weblto-win-*.zip`
`zip` => `webtlo.zip`
В прочих случаях просто ссылка на релиз.
Close #293

Исправить получение ссылки на новый релиз

---

src/composer.json
src/composer.lock

Close #266 
В composer.json добавлен [xmlrpc-polyfill ](https://github.com/gggeek/polyfill-xmlrpc) для замены исключённого из php8+ xml-rpc.
См .https://php.watch/versions/8.0/xmlrpc#alternatives
Проверил docker и standalone версии с помощью этой [сборки ](https://github.com/crazy-max/docker-rtorrent-rutorrent?tab=readme-ov-file)rTorrent+ruTorrent

Добавил php-polyfill-xmlrpc

---

src/css/style.css
src/index.php
src/php/actions/get_user_details.php
src/php/classes/user_details.php
src/scripts/jquery.actions.js

Т.к. статический поддомен форума заблокирован, у многих людей проблемы с авторизацией из-за невозможности получить картинку с капчой.
Продолжая #249, добавил использование прокси в алгоритм получения картинки с капчой при неудачной попытке акторизации. Теперь, если без прокси картинку получить не дуалось, будет вторая попытка уже с прокси.
Саму картинку теперь локально не храним, а выводим на фронт в виде base64 кодированной строки.

Forum Auth. Добавил использование прокси при получении изображения капчи

---

src/back/Settings.php
src/back/Tables/KeepersSeeders.php
src/back/Update/ExcludedKeepersTrait.php
src/back/Update/KeepersReports.php
src/back/Update/Subsections.php
src/php/common/keepers.php

close #272
Добавлена опция в конфиг, в значение которой можно перечислить id хранителей, которых нужно исключить из локальных данных.
Указанные хранители не будут отображаться в списке раздач, не будут учитываться в количестве хранителей раздачи и вообще не будут присутствовать в локальной БД.
На текущий момент, заполнение вручную. Найти секцию  `reports` в `config.ini`, внести ид через запятую или `|`. 
Например:
```
[reports]
exclude_keepers_ids="1234,4312,3212"
```

Keepers. Add exluded list

---

.github/workflows/sub-build-docker.yml

It's unclear whether GHCR login username should be `github.actor` or `github.repository_owner` - looks like real auth being done via GITHUB_TOKEN

Add pushing to GH Container Registry

---

src/css/style.css
src/index.php
src/scripts/jquery.actions.js
src/scripts/jquery.common.js
src/scripts/jquery.settings.func.js
src/scripts/jquery.settings.init.js
src/scripts/jquery.subsections.init.js
src/scripts/jquery.topics.func.js
src/scripts/jquery.topics.init.js

close #332, close #333 
Добавлена ссылка на выбранный хранимый подраздел.
Добавлены ссылки на хранимые подразделы.
Добавлена ссылка на свой профиль.
Добавлена возможность открыть профиль хранителя из списка раздач.
`Alt+click` или `middle-click` (колёсико).
Дабл клик заменяет строку поиска по хранителю на выбранного.
Ctrl + даблклик - добавляет хранителя в список поиска.

Добавлены ссылки на профиль хранителя и выбранный хранимый подраздел из настроек

---

src/back/AppContainer.php
src/back/Clients/ClientInterface.php
src/back/Clients/Data/Torrent.php
src/back/Clients/Data/Torrents.php
src/back/Clients/Deluge.php
src/back/Clients/Flood.php
src/back/Clients/Qbittorrent.php
src/back/Clients/Rtorrent.php
src/back/Clients/Traits/TopicIdSearch.php
src/back/Clients/Transmission.php
src/back/Clients/Utorrent.php
src/back/Config/TopicControl.php
src/php/common/control.php
src/php/common/tor_clients.php

Close #370 #371
- Добавлено DTO Torrent и Torrents для хранения данных о раздачах в торрент клиентах
- Для поддерживаемых клиентов добавлен алгоритм получения более реалистичного процента скачивания, в случаях, когда выбраны не все файлы 
```
deluge 2.1.1 - можно проверить процент по каждому файлу, и прикинуть общий реальный процент выбранного и скачанного;
flood - поверх qbit, rtorrent, trans, etc, данных о реальном проценте выбранного и скачанного я не нашёл;
qbit 4.5 - есть тег availability, который если не равен -1 представляет собой тот самый процент;
rtorrent хз какой - есть количество "байт осталось". Если выбрана часть раздачи, то там всегда будет какое-то значение. Можно посчитать реальный процент раздачи;
trans 3.0 - просто использовать percentComplete вместо percentDone …
```

Улучшение работы с торрентами

---

src/back/Action/TopicControl.php
src/back/Clients/Qbittorrent.php

После внедрения данного [ПР](https://github.com/qbittorrent/qBittorrent/pull/20532), версию webApi qBit подняли до 2.11 и сломали обратную совместимость.
- Статусы раздачи `paused` заменены на `stopped`, из-за чего сломалась регулировка раздач.
- Отправляемые комманды для запуска/остановки раздач изменены с `resume/pause` на `start/stop`, из-за чего сломалась автоматическая регулировка и ручной запуск/остановка.
---
- Добавил проверку версии webApi при попытке изменения статуса раздачи. 
- В зависимости от версии используется соотверствующая команда.
- Добавлен список возможных статусом "остановленной" раздачи.

Исправляем поломанное webApi qBit 5.0+

---

src/back/External/Forum/SummaryReport.php

Added debug messages to trace the error "No reports found for given user" when the log level is "Debug". 
The parsePostIdFromReportSearch method will call the logger, therefore, it will no longer be static.

Debug messages to trace the error "No reports found for given user"

---

src/back/Action/SendKeeperReports.php
src/back/Module/Report/CreateReport.php
src/back/Module/Report/EmptyFoundTopicsException.php

Если подраздел заявлен как хранимый (добавлен в список подразделов в настройках), но нет фактически хранимых раздач из этого подраздела, то теперь отметка "хранения" будет сниматься с такого подраздела и всех его раздач в API, при отправке отчётов.
Данное поведение исправит ситуацию, когда хранитель удалил все хранимые раздачи, но не удалил подраздел из настроек и всё равно считался хранителем уже удалённых раздач.

Unset kept status for forum without kept topics on report send

---

src/back/Clients/ClientInterface.php
src/back/Storage/Table/Torrents.php
src/index.php
src/php/actions/exec_actions_topics.php
src/scripts/jquery.clients.func.js
src/scripts/jquery.topics.func.js
src/scripts/jquery.topics.init.js

Fix #342 
- Обновил некоторый js функционал.
- Добавил в параметры применимых действий выбранный в фильтрах торрент-клиент. 
- Обновил уведомление при попытке удаления раздач.
- Добавил уведомление в лог при удалении раздач без выбраного торрент-клиента.
- Теперь "действия" над раздачами (метка, запуск/остановка, удаление) будут применяться только к раздачам выбранного клиента, если он выбран.
Удаление раздач с вкладки "Хранимые дубликаты" всё ещё будет удалять раздачи ВО ВСЕХ клиентах, т.к. фильтр по клиенту не доступен.

Refactor toolbar actions

---

src/php/actions/get_recovery_list.php

When the same torrent was in different clients, the output list contained duplicate entries, i.e. the same torrent was listed multiple times, which is not needed for the report of recovery list

The output list contained duplicate entires

---

.php-cs-fixer.php
src/back/Module/Report/CreateReport.php
src/back/TopicList/Validate.php

Для версий 3.70+ было изменено поведение правила `operator_linebreak`, см. [release 3.70](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.70.0), [PR 8417](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8417)
Поправил правила и некоторые файлы.

Обновление правил php-cs-fixer для версии 3.70+

---

src/php/actions/exec_actions_topics.php
src/scripts/jquery.topics.func.js

Булевые типы `true/false` преобразовывались в строки в `$_POST`, что ломало логику. 
Теперь передаётся json, вместо post-параметров.

Исправлено удаление файлов при удалении раздачи из клиента

---

src/back/Clients/Transmission.php

Fix #438 
При длительном выполнении алгоритма, трансмишн сбрасывает сессию и нужно подставлять новый заголовок авторизации.
Как оказалось, метод `withAddedHeader` не подходит, т.к. он дописывает значение в конец массива заголовка, что неверно. Заменено на `withHeader`, который заменяет значение.

Clients. Fix transmission auth token update

---

src/back/Action/SendKeeperReports.php
src/back/Data/KeeperPermissions.php
src/back/External/ApiReportClient.php
src/back/Module/Report/SendReport.php
src/back/Update/KeepersReports.php
src/back/Update/Subsections.php

С недавних пор кандидат в хранители нзапрещено получать данные и изменять статус хранения раздач в подразделах, которые ему не отметил куратор.
- Добавлен класс `KeeperPermissions` для хранения текущего "статуса" хранителя.
- Добавлен метод для получения и обработки статуса хранителя и его "отмеченных" в API хранимых подразделов.
- Добавлены проверки возможности взаимодействия кандидата в хранителя с различными процессами:
- получение раздач в хранимых подразделах
- получение списков хранителей в этих подразделах
- отправка отчётов по таким подразделам
В случае отсутствия доступа будет уведомление вида:
```
INFO: Обнаружены ограничения доступа к API отчётов. {"allowed_subforums":[1030]}
NOTICE: У кандидата в хранители нет доступа к указанным подразделам. Обратитесь к куратору. …
```

Обработка ограничений доступа к API для кандидатов в хранители
